[package]
name = "json_formatter"
version = "26.8.31"
edition = "2024"


[dependencies]
is-terminal = "0.4.17"
json5 = "1.3.1"
serde_json = {
    version = "1.0.151",
    features = ["preserve_order"]
}


[build-dependencies]
winres = "0.1.12"


[profile.release]
opt-level = "z"          # “z” = maximum size reduction (equivalent to -C opt-level=s)
lto = true               # Link‑time optimisation
codegen-units = 1        # Better optimisation (single codegen unit)
panic = "abort"          # Remove unwinding tables
debug = false            # No debug info
strip = true             # Strip symbols (requires rustc 1.56+)
rpath = false            # Don't embed runtime library paths
incremental = false      # Disable incremental compilation (cleaner builds)


